//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputMooringCalculation
    {
        public int Id { get; set; }
        public Nullable<int> PortId { get; set; }
        public string PortName { get; set; }
        public Nullable<decimal> Xch { get; set; }
        public Nullable<decimal> Ych { get; set; }
        public Nullable<decimal> Zch { get; set; }
        public Nullable<decimal> Xbl { get; set; }
        public Nullable<decimal> Ybl { get; set; }
        public Nullable<decimal> Zbl { get; set; }
        public Nullable<decimal> l0 { get; set; }
        public Nullable<decimal> E { get; set; }
        public Nullable<decimal> n { get; set; }
        public Nullable<decimal> a { get; set; }
        public Nullable<decimal> MBSrope { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> OldInputId { get; set; }
        public int VesselID { get; set; }
    }
}
