//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUsedWinchTbl
    {
        public int Id { get; set; }
        public Nullable<int> OperationID { get; set; }
        public string GridID { get; set; }
        public Nullable<System.DateTime> OPDateFrom { get; set; }
        public Nullable<System.DateTime> OPDateTo { get; set; }
        public Nullable<int> WinchId { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<decimal> RunningHours { get; set; }
        public Nullable<int> RopeTail { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public string Lead { get; set; }
        public string Lead1 { get; set; }
        public int VesselID { get; set; }
        public Nullable<bool> Outboard { get; set; }
    }
}
