//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Nid { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> VesselId { get; set; }
        public string VesselName { get; set; }
        public string FleetName { get; set; }
        public string FleetType { get; set; }
        public Nullable<System.DateTime> NcDate { get; set; }
        public string NonConfirmity { get; set; }
        public string NCtype { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Rank { get; set; }
        public string AdminAkn { get; set; }
        public string MasterAkn { get; set; }
        public string HODAkn { get; set; }
        public string Acknowledge { get; set; }
        public Nullable<System.DateTime> AcknDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string FileNames { get; set; }
    }
}
