//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputBasicWindPartameter
    {
        public int Id { get; set; }
        public Nullable<int> PortId { get; set; }
        public string PortName { get; set; }
        public string Name { get; set; }
        public string Notation { get; set; }
        public Nullable<decimal> MainValue { get; set; }
        public string Units { get; set; }
        public Nullable<System.DateTime> OutputDate { get; set; }
        public int VesselID { get; set; }
    }
}
