//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputMorringForcesCalculation
    {
        public int Id { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<int> PortId { get; set; }
        public string PortName { get; set; }
        public Nullable<decimal> Xch { get; set; }
        public Nullable<decimal> Ych { get; set; }
        public Nullable<decimal> Zch { get; set; }
        public Nullable<decimal> Xbl { get; set; }
        public Nullable<decimal> Ybl { get; set; }
        public Nullable<decimal> Zbl { get; set; }
        public Nullable<decimal> l1 { get; set; }
        public Nullable<decimal> ΔZi { get; set; }
        public Nullable<decimal> a { get; set; }
        public Nullable<decimal> n { get; set; }
        public Nullable<decimal> ai { get; set; }
        public Nullable<decimal> MBSrope { get; set; }
        public Nullable<decimal> MBS { get; set; }
        public Nullable<decimal> Ei { get; set; }
        public Nullable<decimal> cosθi { get; set; }
        public Nullable<decimal> φi { get; set; }
        public Nullable<decimal> cosφi { get; set; }
        public Nullable<decimal> l0 { get; set; }
        public Nullable<decimal> Li { get; set; }
        public Nullable<decimal> ki { get; set; }
        public Nullable<decimal> kyi { get; set; }
        public Nullable<decimal> kyi_Xch { get; set; }
        public Nullable<decimal> kyi_Xch2 { get; set; }
        public Nullable<decimal> Fyi { get; set; }
        public Nullable<decimal> Ti { get; set; }
        public Nullable<decimal> FSi { get; set; }
        public Nullable<System.DateTime> OutputDate { get; set; }
        public int VesselID { get; set; }
    }
}
