//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int Id { get; set; }
        public string RPrefix { get; set; }
        public Nullable<int> RNumber { get; set; }
        public Nullable<System.DateTime> ReviseDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string CreateBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> Mid { get; set; }
        public string RevisionType { get; set; }
        public string Content { get; set; }
        public string ContentPath { get; set; }
        public string Status { get; set; }
        public string RevisionText { get; set; }
    }
}
