//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubSubMenu
    {
        public int SubSubId { get; set; }
        public Nullable<int> SubId { get; set; }
        public string SubSubMenuName { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string AreaName { get; set; }
        public string Role { get; set; }
        public Nullable<int> MId { get; set; }
    }
}
