//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string ContactNumber { get; set; }
        public string UserRole { get; set; }
        public string PermissionType { get; set; }
        public string Vessels { get; set; }
        public string FleetNames { get; set; }
        public string FleetTypes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserID { get; set; }
        public Nullable<int> LoginType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
