//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MaxInspectDate
    {
        public Nullable<System.DateTime> InspectDate { get; set; }
        public Nullable<int> RopeID { get; set; }
        public int VesselID { get; set; }
    }
}
