//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AbrasionDetails
    {
        public int VesselID { get; set; }
        public string VesselName { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<System.DateTime> InspectDate { get; set; }
        public Nullable<int> AverageRating_A { get; set; }
        public Nullable<int> AverageRating_B { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> InstalledDate { get; set; }
        public string RopeType { get; set; }
    }
}
