//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OperationRecords
    {
        public int OPId { get; set; }
        public Nullable<System.DateTime> CastDatetime { get; set; }
        public string BirthName { get; set; }
        public Nullable<System.DateTime> FastDatetime { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> RopeTypeId { get; set; }
        public string RopeType { get; set; }
        public int RopeId { get; set; }
        public string PortName { get; set; }
        public string FacilityName { get; set; }
        public string MooringType { get; set; }
        public string BerthSide { get; set; }
        public Nullable<int> WindSpeed { get; set; }
        public string AnySquall { get; set; }
        public Nullable<decimal> CurrentSpeed { get; set; }
        public string Berth_exposed_SeaSwell { get; set; }
        public string SurgingObserved { get; set; }
        public string Any_Affect_Passing_Traffic { get; set; }
        public string Ship_was_continuously_contact_with_fender { get; set; }
        public string Any_Rope_Damaged { get; set; }
        public Nullable<int> AirTemprature { get; set; }
        public string Lead { get; set; }
        public string Lead1 { get; set; }
        public string VesselName { get; set; }
        public int ImoNo { get; set; }
        public Nullable<int> RopeDamaged { get; set; }
        public string BirthType { get; set; }
        public string PortDetails { get; set; }
    }
}
