//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RopesOverdueInspection
    {
        public Nullable<System.DateTime> InspectionDueDate { get; set; }
        public int RopeId { get; set; }
        public int VesselID { get; set; }
        public Nullable<System.DateTime> OutofServiceDate { get; set; }
    }
}
