//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ReportInspectionStatus
    {
        public int Id { get; set; }
        public string VesselName { get; set; }
        public string InspectBy { get; set; }
        public Nullable<System.DateTime> InspectDate { get; set; }
        public Nullable<int> LooseETypeId { get; set; }
        public string LooseEquipmentType { get; set; }
        public string Number { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RopeTail { get; set; }
        public int FleetID { get; set; }
        public string FleetName { get; set; }
        public int FleetTypeID { get; set; }
        public string FleetType { get; set; }
        public int OtherID { get; set; }
        public string OtherName { get; set; }
        public int OtherType { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public System.DateTime DateBuilt { get; set; }
    }
}
