//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Abrasion_Combined_Details
    {
        public Nullable<int> RopeId { get; set; }
        public int ImoNo { get; set; }
        public string VesselName { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> AverageRating_A { get; set; }
        public Nullable<int> AverageRating_B { get; set; }
        public Nullable<int> WinchId { get; set; }
        public string AssignedNumber { get; set; }
        public string Location { get; set; }
        public Nullable<int> InspectionId { get; set; }
        public string InspectBy { get; set; }
        public Nullable<System.DateTime> InspectDate { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
    }
}
