//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Notifications
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string NotificationText { get; set; }
        public Nullable<bool> Acknowledge { get; set; }
        public string ShipActionTaken { get; set; }
        public string AckRecord { get; set; }
        public Nullable<System.DateTime> NotificationDueDate { get; set; }
        public string VesselName { get; set; }
        public int ImoNo { get; set; }
        public string Flag { get; set; }
        public int FleetNameID { get; set; }
        public int FleetTypeID { get; set; }
        public int TradeAreaID { get; set; }
        public string FleetName { get; set; }
        public string FleetType { get; set; }
        public string TradeArea { get; set; }
        public System.DateTime DateBuilt { get; set; }
        public Nullable<int> TotalComments { get; set; }
        public int VesselId { get; set; }
        public Nullable<System.DateTime> AcknDateTime { get; set; }
        public string AcknBy { get; set; }
        public string FullName { get; set; }
    }
}
