//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRopeSummaryInspection
    {
        public int Id { get; set; }
        public string InspectBy { get; set; }
        public Nullable<System.DateTime> InspectDate { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<int> WinchId { get; set; }
        public Nullable<int> ExternalRating_A { get; set; }
        public Nullable<int> InternalRating_A { get; set; }
        public Nullable<int> AverageRating_A { get; set; }
        public Nullable<decimal> LengthOFAbrasion_A { get; set; }
        public Nullable<decimal> DistanceOutboard_A { get; set; }
        public Nullable<decimal> CutYarnCount_A { get; set; }
        public Nullable<decimal> LengthOFGlazing_A { get; set; }
        public Nullable<int> RopeTail { get; set; }
        public Nullable<int> ExternalRating_B { get; set; }
        public Nullable<int> InternalRating_B { get; set; }
        public Nullable<int> AverageRating_B { get; set; }
        public Nullable<decimal> LengthOFAbrasion_B { get; set; }
        public Nullable<decimal> DistanceOutboard_B { get; set; }
        public Nullable<decimal> CutYarnCount_B { get; set; }
        public Nullable<decimal> LengthOFGlazing_B { get; set; }
        public string Chafe_guard_condition { get; set; }
        public Nullable<int> Twist { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public Nullable<int> InspectionId { get; set; }
        public int VesselID { get; set; }
        public Nullable<int> RopeTypeId { get; set; }
        public string RopeConstruction { get; set; }
        public Nullable<decimal> DiaMeter { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> MBL { get; set; }
        public Nullable<decimal> LDBF { get; set; }
        public Nullable<decimal> WLL { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> InstalledDate { get; set; }
        public string RopeTagging { get; set; }
        public Nullable<System.DateTime> OutofServiceDate { get; set; }
        public string ReasonOutofService { get; set; }
        public string OtherReason { get; set; }
        public string DamageObserved { get; set; }
        public string IncidentReport { get; set; }
        public Nullable<int> MooringOperationID { get; set; }
        public Nullable<decimal> CurrentRunningHours { get; set; }
        public Nullable<int> MaxRunningHours { get; set; }
        public Nullable<int> MaxMonthsAllowed { get; set; }
        public Nullable<System.DateTime> InspectionDueDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> StartCounterHours { get; set; }
        public string UniqueID { get; set; }
        public Nullable<decimal> CostUsd { get; set; }
    }
}
