//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinchRotation
    {
        public int Id { get; set; }
        public Nullable<int> RopeId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> WinchId { get; set; }
        public string Lead { get; set; }
        public Nullable<decimal> RunningHours { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int VesselID { get; set; }
    }
}
