//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Cid { get; set; }
        public Nullable<int> Nid { get; set; }
        public string Comment1 { get; set; }
        public string CommentBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
    }
}
