//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string EstablishYear { get; set; }
        public string TotalEmployee { get; set; }
        public string Website { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string FaxNo { get; set; }
        public string contectNo { get; set; }
    }
}
