//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSmartMenu
    {
        public int Id { get; set; }
        public string SmartMenuContent { get; set; }
        public string HtmlContent { get; set; }
        public string SmartMenuContentExport { get; set; }
        public string HtmlContentExport { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
