//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempDocsPage
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> Mid { get; set; }
        public Nullable<int> Subid { get; set; }
        public Nullable<int> SubSubid { get; set; }
    }
}
