//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public string Role { get; set; }
        public string EmailId { get; set; }
        public string VesselName { get; set; }
        public string VesselID { get; set; }
        public string FleetName { get; set; }
        public string FleetType { get; set; }
        public string AssignVal { get; set; }
    }
}
