//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselDetail
    {
        public int Id { get; set; }
        public string VesselName { get; set; }
        public int ImoNo { get; set; }
        public string Flag { get; set; }
        public int FleetNameID { get; set; }
        public int FleetTypeID { get; set; }
        public int TradeAreaID { get; set; }
        public string FleetName { get; set; }
        public string FleetType { get; set; }
        public string TradeArea { get; set; }
        public System.DateTime DateBuilt { get; set; }
    
        public virtual tblCommon tblCommon { get; set; }
        public virtual tblCommon tblCommon1 { get; set; }
        public virtual tblCommon tblCommon2 { get; set; }
    }
}
