//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OperationWiseRopes
    {
        public int Id { get; set; }
        public Nullable<int> OperationID { get; set; }
        public string AssignedNumber { get; set; }
        public string Location { get; set; }
        public string CertificateNumber { get; set; }
        public string Lead { get; set; }
        public string Lead1 { get; set; }
        public int VesselID { get; set; }
    }
}
