//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ReportAssignRopeToWinch
    {
        public int id { get; set; }
        public string certificatenumber { get; set; }
        public string assignednumber { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Outboard { get; set; }
    }
}
