//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RopeDamages
    {
        public int Id { get; set; }
        public Nullable<int> MOPId { get; set; }
        public Nullable<int> RopeId { get; set; }
        public string AssignedNumber { get; set; }
        public string IncidentReport { get; set; }
        public string IncidentActlion { get; set; }
        public string CertificateNumber { get; set; }
        public string DamageReason { get; set; }
        public int VesselID { get; set; }
        public string VesselName { get; set; }
    }
}
