//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipment49Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRopesDisposed
    {
        public int RopeId { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string CertificateNumber { get; set; }
        public string DisposalPortName { get; set; }
        public string ReceptionFacilityName { get; set; }
        public int VesselID { get; set; }
        public string VesselName { get; set; }
        public Nullable<int> RopeTail { get; set; }
    }
}
